# DO NOT EDIT THIS FILE
# Instead, copy example_config.user.sh to config.user.sh and copy that file

# Mandatory environment variables
# The following environment variables should be set in config.user.sh

# LOCAL_DATA_DIR
# KACHERY_STORAGE_DIR
# MONGO_DATA_DIR
# LABBOX_EPHYS_PORT

# Optional environment variables
# The following environment variables may be overridden in config.user.sh

export MONGO_ADMIN_USER=admin
export MONGO_ADMIN_PASSWORD=test-admin-password
export MONGO_USER=labbox
export MONGO_PASSWORD=test-labbox-password
export MONGO_PORT=27017

export JUPYTERLAB_PORT=8888
export JUPYTERLAB_TOKEN=secret-token

export LABBOX_EPHYS_KILL_CODE=killcode
